version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: inteamfit
      POSTGRES_PASSWORD: inteamfit
      POSTGRES_DB: inteamfit
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
